name: stackoverflow_search_app
description: "A Flutter application for searching Stack Overflow."
# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.4
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  freezed: ^2.5.7
  json_serializable: ^6.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Assets configuration
  assets:
    - assets/
